"""Which KPIs each fact table unlocks. Generated — do not edit.

    python tools/gen_table_kpis.py

Derived by removing one table at a time from a full synthetic dataset and
recording which KPIs stop computing, across every archetype and every pack. See
`tools/gen_table_kpis.py` for why this is derived rather than declared, and
`kpi_maker/ingest/quality.py` for what reads it.
"""
from __future__ import annotations

from typing import Dict, List

TABLE_KPIS: Dict[str, List[str]] = {
    "backlog": [
        "backlog_cover_months",
        "backlog_growth_yoy",
        "book_to_bill",
        "bookings_growth_yoy",
    ],
    "buyers": [
        "active_buyers",
        "cost_per_new_buyer",
        "new_buyer_share",
        "repeat_purchase_rate",
    ],
    "gmv": [
        "average_transaction_value",
        "gmv_growth_yoy",
        "gmv_ttm",
        "take_rate",
    ],
    "headcount": [
        "arr_per_fte",
        "attrition_rate",
        "employee_attrition",
        "headcount_growth",
        "personnel_cost_ratio",
        "revenue_per_fte",
        "revenue_per_head",
        "workforce_size",
    ],
    "inventory": [
        "finished_stock_cover",
        "inventory_cover_days",
        "inventory_turns",
        "stockout_days",
    ],
    "liquidity": [
        "demand_growth_yoy",
        "listing_sell_through",
        "match_rate",
        "supply_demand_ratio",
        "supply_growth_yoy",
    ],
    "marketing": [
        "acquisition_spend",
        "acquisition_spend_growth",
        "cost_per_new_buyer",
        "cost_per_order",
        "lead_to_mql_rate",
        "marketing_efficiency_ratio",
        "mql_to_sql_rate",
    ],
    "monthly_financials": [
        "acquisition_spend",
        "acquisition_spend_growth",
        "active_buyers",
        "aov",
        "arpa",
        "arr",
        "arr_growth_yoy",
        "arr_per_fte",
        "attrition_rate",
        "average_bill_rate",
        "average_selling_price",
        "average_transaction_value",
        "backlog_cover_months",
        "backlog_growth_yoy",
        "bench_ratio",
        "billings",
        "blended_cac",
        "book_to_bill",
        "bookings_growth_yoy",
        "burn_multiple",
        "cac_payback_months",
        "capex_intensity",
        "cart_abandonment_rate",
        "cash_runway",
        "contribution_margin",
        "conversion_rate",
        "cost_per_new_buyer",
        "cost_per_order",
        "crpo_growth",
        "customer_count",
        "demand_growth_yoy",
        "discount_rate",
        "ebitda_margin",
        "employee_attrition",
        "enterprise_customers",
        "equipment_availability",
        "expansion_share",
        "fcf_margin",
        "finished_stock_cover",
        "free_cash_flow_margin",
        "free_cash_flow_ratio",
        "gmv_growth_yoy",
        "gmv_ttm",
        "gross_margin",
        "gross_margin_pct",
        "grr",
        "headcount_growth",
        "inventory_cover_days",
        "inventory_turns",
        "lead_to_mql_rate",
        "line_performance",
        "listing_sell_through",
        "logo_churn_rate",
        "ltv_cac_ratio",
        "magic_number",
        "marketing_efficiency_ratio",
        "marketing_intensity",
        "marketing_pct_revenue",
        "match_rate",
        "mql_to_sql_rate",
        "net_new_arr",
        "net_revenue",
        "new_buyer_share",
        "nrr",
        "oee",
        "operating_margin",
        "opex_ratio",
        "orders_count",
        "overhead_intensity",
        "personnel_cost_ratio",
        "quick_ratio",
        "realisation_rate",
        "repeat_purchase_rate",
        "return_rate",
        "revenue_concentration_top10",
        "revenue_growth_yoy",
        "revenue_per_fte",
        "revenue_per_head",
        "revenue_ttm",
        "rnd_intensity",
        "rnd_pct_revenue",
        "rule_of_40",
        "sales_intensity",
        "schedule_utilisation",
        "scrap_rate",
        "senior_hours_share",
        "sessions",
        "shipped_volume_growth_yoy",
        "sm_pct_revenue",
        "stockout_days",
        "supply_demand_ratio",
        "supply_growth_yoy",
        "take_rate",
        "utilisation_rate",
        "workforce_size",
    ],
    "mrr_movements": [
        "arpa",
        "burn_multiple",
        "cac_payback_months",
        "customer_count",
        "enterprise_customers",
        "expansion_share",
        "grr",
        "logo_churn_rate",
        "ltv_cac_ratio",
        "magic_number",
        "net_new_arr",
        "nrr",
        "quick_ratio",
        "revenue_concentration_top10",
    ],
    "orders": [
        "aov",
        "cost_per_order",
        "discount_rate",
        "net_revenue",
        "orders_count",
        "return_rate",
        "revenue_per_fte",
    ],
    "pipeline": [
        "blended_cac",
        "ltv_cac_ratio",
        "pipeline_coverage",
        "pipeline_created",
        "sales_cycle_days",
        "win_rate",
    ],
    "product_usage": [
        "activation_rate",
        "engagement_ratio",
        "time_to_value_days",
    ],
    "production": [
        "equipment_availability",
        "line_performance",
        "oee",
        "schedule_utilisation",
        "scrap_rate",
    ],
    "sales_capacity": [
        "arr_per_rep",
        "quota_attainment",
        "rep_ramp_months",
    ],
    "shipments": [
        "average_selling_price",
        "discount_rate",
        "return_rate",
        "shipped_volume_growth_yoy",
    ],
    "timesheets": [
        "average_bill_rate",
        "bench_ratio",
        "realisation_rate",
        "senior_hours_share",
        "utilisation_rate",
    ],
    "traffic": [
        "cart_abandonment_rate",
        "conversion_rate",
        "sessions",
    ],
}
