"""Portable outputs from one computed snapshot. No LLM calls or browser renderer."""

from __future__ import annotations

import csv
import html
import io
from pathlib import Path

from fpdf import FPDF
from pptx import Presentation
from pptx.chart.data import CategoryChartData
from pptx.dml.color import RGBColor
from pptx.enum.chart import XL_CHART_TYPE
from pptx.util import Inches, Pt

from ..render.report import FONT_CANDIDATES


def fmt(value):
    return "Unavailable" if value is None else f"{value:,.4g}"


def svg_chart(spec, result):
    rows = result["rows"]
    vals = [r["values"][0] for r in rows]
    low, high = (
        min([0] + [v for v in vals if v is not None]),
        max([0] + [v for v in vals if v is not None]),
    )
    span = high - low or 1

    if spec.chart == "line":

        def px(i):
            return 80 + i * 610 / max(1, len(rows) - 1)

        def py(v):
            return 270 - (v - low) / span * 220

        parts = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 350">']
        parts.append(
            f'<line x1="80" x2="690" y1="{py(0)}" y2="{py(0)}" stroke="#64748b"/>'
        )
        for i, (row, value) in enumerate(zip(rows, vals)):
            if value is not None:
                if i and vals[i - 1] is not None:
                    parts.append(
                        f'<line x1="{px(i - 1)}" y1="{py(vals[i - 1])}" x2="{px(i)}" y2="{py(value)}" stroke="{spec.color}" stroke-width="3"/>'
                    )
                parts.append(
                    f'<circle cx="{px(i)}" cy="{py(value)}" r="4" fill="{spec.color}"/>'
                )
            if i % max(1, (len(rows) + 5) // 6) == 0:
                parts.append(
                    f'<text x="{px(i) - 20}" y="305" font-size="12">{html.escape(row["label"][:12])}</text>'
                )
        parts += [
            f'<text x="0" y="50" font-size="12">{fmt(high)}</text>',
            f'<text x="0" y="270" font-size="12">{fmt(low)}</text>',
        ]
        return "".join(parts) + "</svg>"
    if spec.chart == "table":
        parts = [
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 {max(80, len(rows) * 30 + 20)}">'
        ]
        for i, (row, value) in enumerate(zip(rows, vals)):
            parts.append(
                f'<text x="5" y="{25 + i * 30}" font-size="14">{html.escape(row["label"][:60])}</text><text x="650" y="{25 + i * 30}" font-size="14">{fmt(value)}</text>'
            )
        return "".join(parts) + "</svg>"

    def x(v):
        return 210 + (v - low) / span * 450

    zero = x(0)
    height = max(100, 40 + len(rows) * 30)
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 {height}" role="img" aria-label="{html.escape(spec.measures[0].name, quote=True)}">'
    ]
    parts.append(
        f'<line x1="{zero}" x2="{zero}" y1="10" y2="{height - 15}" stroke="#64748b"/>'
    )
    for i, (r, value) in enumerate(zip(rows, vals)):
        y = 22 + i * 30
        parts.append(
            f'<text x="5" y="{y + 4}" font-size="13">{html.escape(r["label"][:25])}</text>'
        )
        if value is not None:
            start, end = sorted([zero, x(value)])
            parts.append(
                f'<rect x="{start}" y="{y - 12}" width="{max(end - start, 1)}" height="20" fill="{spec.color}"/>'
            )
        parts.append(f'<text x="680" y="{y + 4}" font-size="13">{fmt(value)}</text>')
    return "".join(parts) + "</svg>"


def export(spec, result, kind, synthetic=False):
    basis = (
        "Synthetic demonstration data. Not real tournament or company results."
        if synthetic
        else "Uploaded data. Descriptive analysis; no causal or clinical conclusions."
    )
    notes = [
        basis,
        "Measures use the selected filters and cleaning steps. No values are generated by AI.",
    ] + result["warnings"]
    if spec.context:
        notes.append("Context: " + spec.context)
    notes += [f"Filter: {f.column} {f.operator} {f.value}." for f in spec.filters]
    notes.append(
        f"Cleaning: trim whitespace {'on' if spec.trim_text else 'off'}; remove exact duplicates {'on' if spec.drop_duplicates else 'off'}."
    )
    if kind == "csv":
        stream = io.StringIO()
        writer = csv.writer(stream)

        # Neutralize spreadsheet formulas in user-controlled text cells.
        def safe(v):
            return (
                "'" + v
                if isinstance(v, str) and v.lstrip().startswith(("=", "+", "-", "@"))
                else v
            )

        writer.writerow(["Group"] + [safe(m.name) for m in spec.measures] + ["Records"])
        for r in result["rows"]:
            writer.writerow([safe(r["label"])] + r["values"] + [r["records"]])
        return stream.getvalue().encode("utf-8-sig"), "text/csv"
    if kind == "html":
        esc = html.escape
        parts = [
            f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{esc(spec.title)}</title><style>body{{font:16px system-ui;color:#172033;max-width:1000px;margin:40px auto;padding:20px}}table{{border-collapse:collapse;width:100%}}td,th{{padding:10px;border-bottom:1px solid #ddd;text-align:left}}svg{{width:100%;height:auto}}p{{line-height:1.6}}</style><h1>{esc(spec.title)}</h1><p>{esc(basis)}</p>'
        ]
        for section in spec.sections:
            parts.append(f"<h2>{section.title()}</h2>")
            if section == "summary":
                parts += [f"<p>{esc(s)}</p>" for s in result["summary"]]
            elif section == "quality":
                parts += [f"<p>{esc(s)}</p>" for s in notes]
            elif section == "chart":
                parts.append("<p>First metric by group.</p>")
                parts.append(svg_chart(spec, result))
            else:
                parts.append(
                    "<table><thead><tr><th>Group</th>"
                    + "".join(f"<th>{esc(m.name)}</th>" for m in spec.measures)
                    + "</tr></thead><tbody>"
                )
                parts += [
                    "<tr><td>"
                    + esc(r["label"])
                    + "</td>"
                    + "".join(f"<td>{fmt(v)}</td>" for v in r["values"])
                    + "</tr>"
                    for r in result["rows"]
                ]
                parts.append("</tbody></table>")
        return ("".join(parts) + "</html>").encode(), "text/html"
    if kind == "pdf":
        pdf = FPDF()
        family = "Helvetica"
        for name, regular, bold, _ in FONT_CANDIDATES:
            if Path(regular).is_file():
                pdf.add_font(name, "", regular)
                pdf.add_font(name, "B", bold if Path(bold).is_file() else regular)
                family = name
                break
        pdf.set_margins(18, 18, 18)
        pdf.set_auto_page_break(True, 18)

        def line(text, size=11, bold=False):
            if family == "Helvetica":
                text = text.encode("latin-1", "replace").decode("latin-1")
            pdf.set_font(family, "B" if bold else "", size)
            pdf.multi_cell(0, 7, text, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)

        pdf.add_page()
        line(spec.title, 22, True)
        line(basis, 10)
        for section in spec.sections:
            if section == "chart":
                chart_height = (
                    76
                    if spec.chart == "line"
                    else max(22, (40 + len(result["rows"]) * 30) * 172 / 800)
                )
                if pdf.get_y() + chart_height + 26 > 275:
                    pdf.add_page()
                line(spec.measures[0].name, 18, True)
                line(
                    "First metric by group. Exact values are listed in the results.", 10
                )
                # Vector chart: portable, searchable labels, no Kaleido dependency.
                pdf.image(io.BytesIO(svg_chart(spec, result).encode()), w=172)
                pdf.ln(4)
            else:
                line(section.title(), 16, True)
                if section == "summary":
                    for s in result["summary"]:
                        line(s)
                elif section == "quality":
                    for s in notes:
                        line(s, 10)
                else:
                    for r in result["rows"]:
                        line(
                            r["label"]
                            + " | "
                            + " ; ".join(
                                m.name + ": " + fmt(v)
                                for m, v in zip(spec.measures, r["values"])
                            ),
                            10,
                        )
        return bytes(pdf.output()), "application/pdf"
    if kind == "pptx":
        deck = Presentation()
        deck.slide_width, deck.slide_height = Inches(13.333), Inches(7.5)

        def text_slide(title, lines):
            slide = deck.slides.add_slide(deck.slide_layouts[5])
            slide.shapes.title.text = title
            box = slide.shapes.add_textbox(
                Inches(0.7), Inches(1.5), Inches(11.8), Inches(5.4)
            ).text_frame
            box.word_wrap = True
            for i, s in enumerate(lines):
                p = box.paragraphs[0] if i == 0 else box.add_paragraph()
                p.text = s
                p.font.size = Pt(18)
                p.space_after = Pt(12)
            return slide

        text_slide(
            spec.title,
            [
                basis,
                f"{result['included_rows']:,} records included",
                "Generated by MasterBI",
            ],
        )
        for section in spec.sections:
            if section == "summary":
                text_slide("Executive summary", result["summary"])
            elif section == "quality":
                for offset in range(0, len(notes), 5):
                    text_slide("Quality and methodology", notes[offset : offset + 5])
            elif section == "chart" and result["rows"] and spec.chart != "table":
                slide = deck.slides.add_slide(deck.slide_layouts[5])
                slide.shapes.title.text = spec.measures[0].name
                data = CategoryChartData()
                data.categories = [r["label"] for r in result["rows"]]
                data.add_series(
                    spec.measures[0].name, [r["values"][0] for r in result["rows"]]
                )
                chart_type = (
                    XL_CHART_TYPE.LINE
                    if spec.chart == "line"
                    else XL_CHART_TYPE.BAR_CLUSTERED
                )
                chart = slide.shapes.add_chart(
                    chart_type,
                    Inches(0.7),
                    Inches(1.5),
                    Inches(11.8),
                    Inches(5.2),
                    data,
                ).chart
                chart.has_legend = False
                series = chart.series[0]
                series.format.fill.solid()
                series.format.fill.fore_color.rgb = RGBColor.from_string(spec.color[1:])
                series.format.line.color.rgb = RGBColor.from_string(spec.color[1:])
            elif section == "data" or (section == "chart" and spec.chart == "table"):
                for offset in range(0, len(result["rows"]), 6):
                    lines = [
                        r["label"]
                        + ": "
                        + "; ".join(
                            m.name + " " + fmt(v)
                            for m, v in zip(spec.measures, r["values"])
                        )
                        for r in result["rows"][offset : offset + 6]
                    ]
                    text_slide("Computed results", lines)
        stream = io.BytesIO()
        deck.save(stream)
        return (
            stream.getvalue(),
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        )
    raise ValueError("Unknown output format")
