"""Generate the front end's CSS custom properties from the engine's palette.

`web/src/styles.css` used to open with two hand-written `:root` blocks and a
comment claiming they were "the same validated palette the charts use (see
kpi_maker/viz/theme.py)". Nothing asserted it. A dashboard, a PDF and the app
chrome that disagree about what "off track" looks like is the drift this whole
repo keeps finding, and the fix is the usual one: state the fact once and
derive the rest.

`kpi_maker/viz/theme.TOKENS` is that one place. This writes it out as CSS.

    python -m tools.gen_tokens            # rewrite web/src/tokens.css
    python -m tools.gen_tokens --check    # fail if it is out of date

`tests/test_packaging.py` runs the check, so a token changed in Python and not
regenerated here is a red build rather than a silent disagreement.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from kpi_maker.design.tokens import css_block  # noqa: E402
from kpi_maker.viz.theme import TOKENS  # noqa: E402

TARGET = ROOT / "web" / "src" / "tokens.css"

HEADER = """/* Generated by tools/gen_tokens.py — do not edit.
 *
 * Every value here comes from `kpi_maker/viz/theme.TOKENS`, which is what the
 * charts, the PDF and the deck are drawn with. Editing this file by hand makes
 * the app disagree with the artifacts it renders; edit the Python and run
 * `python -m tools.gen_tokens`.
 *
 * Tokens the app needs and the engine has no opinion about — surfaces that
 * only exist in chrome, radii, shadows — live in `styles.css` instead.
 */
"""


def _block(selector: str, mode: str) -> str:
    """One `:root` block.

    The derivation itself moved to `kpi_maker/design/tokens.py` in 7.4c. It
    used to live here, which meant the `-text` twins reached `web/src/tokens.css`
    and nothing else — while `render/dashboard.py` builds its own `:root` from
    the same `TOKENS` and so went on painting chips with graphical values. A
    rule that lives in the tool that writes one of its two consumers is a rule
    the other consumer does not have.
    """
    return "\n".join([f"{selector} {{", css_block(TOKENS[mode], mode), "}"])


def render() -> str:
    return "\n\n".join([
        HEADER.rstrip(),
        _block(":root", "light"),
        _block(':root[data-theme="dark"]', "dark"),
    ]) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the file is out of date")
    args = parser.parse_args()

    wanted = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None

    if args.check:
        if current == wanted:
            print(f"{TARGET.relative_to(ROOT)} is up to date")
            return 0
        print(f"{TARGET.relative_to(ROOT)} is stale — run "
              "`python -m tools.gen_tokens`", file=sys.stderr)
        return 1

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(wanted, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
